% Notch 50 Hz + harmonics with a 3 Hz 3-dB bandwidth, make QA plots for first 3 files.
SUMMARY = apply_batch_notch_folder_50Hz_2( ...
    '/Users/margaridaseabra/20.11scored files/tobenotched', ...
    'pattern','*.mat', ...
    'eegVar','eeg', ...
    'fsVar','eeg_frequency', ...
    'mains',50, ...
    'bw_Hz',3, ...
    'harmonics',true, ...
    'suffix','_notched50Hz_bw3.mat', ...
    'preview_plots',3, ...
    'max_plot_freq',100);
