SUMMARY = run_batch_export_scores('/Users/margaridaseabra/15.11scored files', ...
    'pattern','*_scored.mat', ...
    'out_base','/Users/margaridaseabra/15.11scores', ...
    'epochSec', [], ...                  % leave empty to infer; set to 1 or 5 to force
    'codes', struct('WK',0,'NREM',1,'REM',2,'MA',15), ...
    'ma_thresh_sec',15, ...
    'skip_if_exists',true, ...
    'write_log',true, ...
    'workers',0);
