% Basic: notch 50 Hz + harmonics, save next to originals with *_notched50.mat
SUMMARY = apply_batch_notch_folder_50Hz('/Users/margaridaseabra/signalnotscored/tobenotched', ...
    'pattern','*.mat', ...
    'eegVar','eeg', ...
    'fsVar','eeg_frequency', ...
    'Q',35, ...
    'harmonics',true, ...
    'preview_plots',2);   % show quick before/after for first 2 files
