name: sleep_app
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pywavelets
  - h5py
  - scikit-learn
  - pip
  - pip:
      - seaborn
      - mne