codes = struct('WK',0,'NREM',1,'REM',2,'MA',15);
%%
qcREM = qc_rem_episodes_spectrogram('/Users/margaridaseabra/24.11 signalnotscored/20251001_baseline_mouse1_APP.mat', '/Users/margaridaseabra/24.11scores/20251001_baseline_mouse1_APP_scored_scores_1Hz.csv',...          
          'eegVar','eeg', ...
          'emgVar','emg',  ...
          'fsVar','eeg_frequency', ...
          'fmax',30);
%%
qcMA  = qc_ma_episodes('/Users/margaridaseabra/24.11 signalnotscored/20251001_baseline_mouse1_APP.mat', '/Users/margaridaseabra/24.11scores/20251001_baseline_mouse1_APP_scored_scores_1Hz.csv',...      
          'codes',codes, ...
          'eegVar','eeg', ...
          'emgVar','emg', ...
          'fsVar','eeg_frequency', ...
          'fmax',40);
%%
[scoreDir,scoreBase,~] = fileparts(scoreFile);
qc_rem_mat = fullfile(fileparts(eegFile), [extractBefore(scoreBase,'_scored') '_REM_QC.mat']);
qc_ma_mat  = fullfile(fileparts(eegFile), [extractBefore(scoreBase,'_scored') '_MA_QC.mat']);

apply_qc_to_scores(scoreFile, qc_rem_mat, qc_ma_mat, 'codes',codes);
%%
qcREM = qc_rem_episodes('/Users/margaridaseabra/24.11 signalnotscored/20251001_baseline_mouse1_APP.mat', '/Users/margaridaseabra/24.11scores/20251001_baseline_mouse1_APP_scored_scores_1Hz.csv',...          
          'eegVar','eeg', ...
          'emgVar','emg',  ...
          'fsVar','eeg_frequency', ...
          'fmax',30);
%%
qcREM = plot_one_episodes_spectrogram( ...
    '/Users/margaridaseabra/24.11 signalnotscored/20251001_baseline_mouse1_APP.mat', ...
    '/Users/margaridaseabra/24.11scores/20251001_baseline_mouse1_APP_scored_scores_1Hz.csv', ...
    'eegVar','eeg', ...
    'emgVar','emg', ...
    'fsVar','eeg_frequency');
