%% DRUGS condition 
scores_dir_cropped = '/Users/margaridaseabra/24.11_cropped_3h_washout';

rows_overall_drugs = run_group_sleep_architecture_drugs_overall( ...
    scores_dir_cropped, ...
    'codes', struct('WK',0,'NREM',1,'REM',2,'MA',15), ...
    'includeMA', true, ...
    'ma_thresh_sec', 15, ...
    'reclassify_short_wake_to_MA', true);
%% DRUGS - MAKE STATE PERCENT
out_dir = '/Users/margaridaseabra/24.11_drugs_analysis';

OUT_state = make_state_percent_baseline_vs_drugs_APPvsWT(rows_overall_drugs, out_dir, ...
    'minNperGroupForStats', 3, ...
    'useFDR', false);

out_dir = fullfile(scores_dir_cropped, 'plots_state_percent');
if ~isfolder(out_dir), mkdir(out_dir); end

OUT_bar = plot_state_percent_bar_6h_baseline_vs_drugs_APPvsWT( ...
    rows_overall_drugs, out_dir, ...
    'minNperGroupForStats', 3, ...
    'useFDR', false);

%% 6 hour baseline vs drugs bouts (analysis a) %% RUN THIS FOR PPT

% 6h bout-rate baseline vs drugs (Condition x Genotype)
rows_overall_drugs = readtable( ...
    '/Users/margaridaseabra/24.11_cropped_3h_washout/group_overall_drugs/rows_overall_drugs.csv');

out_dir_3h = '/Users/margaridaseabra/24.11_drugs_analysis';

OUT_bouts3h = plot_bout_rate_6h_baseline_vs_drugs_APPvsWT( ...
                  rows_overall_drugs, out_dir_3h, ...
                  'states', ["WK","MA","NREM","REM","SLEEP"], ...
                  'minNperGroupForStats', 2);

%% progression with baseline for comparison
rows_perhr = readtable('/Users/margaridaseabra/sleep_app_ach_warm/Sleep Architecture Analysis/group_out/group_per_hour.csv');
meta       = readtable('/Users/margaridaseabra/sleep_app_ach_warm/Drugs-AmbTemp-crop-3h+washout/drugs-times-all-mice.xlsx', ...
                       'VariableNamingRule','preserve');

out_dir = '/Users/margaridaseabra/24.11_drugs_progression';

OUT_prog = plot_bouts_per_hour_drugs_progression_APPvsWT( ...
              rows_perhr, meta, ["WK","MA","NREM","REM"], out_dir, ...
              'relHourRange',[-3 5], ...
              'drugWindow_h',6, ...
              'useFDRforStars',true);
out_dir = '/Users/margaridaseabra/24.11_drugs_progression_withBaseline';

OUT_prog = plot_bouts_per_hour_drugs_progression_with_baseline_APPvsWT( ...
              rows_perhr, meta, ["WK","MA","NREM","REM"], out_dir, ...
              'relHourRange',[-3 5], ...
              'drugWindow_h',6, ...
              'showIDs',false, ...
              'useFDRforStars',false, ...
              'minNperGroupForStats',3);


%% duration
out_dir = '/Users/margaridaseabra/24.11_drugs_duration_withBaseline';
OUT_bout = make_boutduration_APPvsWT_baseline_vs_drugs( ...
                rows_overall_drugs, ...
                out_dir, ...
                ["WK","MA","NREM","REM"]);
