OUT = run_group_sleep_architecture('/Users/margaridaseabra/24.11scores', ...
    'pattern','*_scored_scores_1Hz.csv', ...
    'codes', struct('WK',0,'NREM',1,'REM',2,'MA',15), ...
    'includeMA', true, ...
    'ma_thresh_sec', 15, ...
    'reclassify_short_wake_to_MA', true, ...
    'out_dir', fullfile(pwd,'group_out'));

PERHOUR = OUT.per_hour;
out_dir = OUT.out_dir;
states_to_use = ["WK","NREM","REM"];
%%
% 1) baseline + ambtemp (no drugs)
conds_no_drugs = ["baseline","ambtemp"];
OUT_no_drugs = make_percenttime_APPvsWT_3blocks( ...
                    PERHOUR, out_dir, ...
                    states_to_use, conds_no_drugs, ...
                    'showIDs', false);

% 2) baseline + ambtemp + drug
conds_with_drugs = ["baseline","ambtemp","drug"];
OUT_with_drugs = make_percenttime_APPvsWT_3blocks( ...
                     PERHOUR, out_dir, ...
                     states_to_use, conds_with_drugs, ...
                     'showIDs', false);
