scores_dir_cropped = '/Users/margaridaseabra/24.11_cropped_ambtemp';

rows_overall_ambtemp = run_group_sleep_architecture_ambtemp_overall( ...
    scores_dir_cropped, ...
    'codes', struct('WK',0,'NREM',1,'REM',2,'MA',15), ...
    'includeMA', true, ...
    'ma_thresh_sec', 15, ...
    'reclassify_short_wake_to_MA', true);

%% RUN THIS FOR PPT
out_dir = '/Users/margaridaseabra/24.11_ambtemp_analysis';

OUT_state = make_state_percent_baseline_vs_ambtemp_APPvsWT(rows_overall_ambtemp, out_dir, ...
    'minNperGroupForStats', 3, ...
    'useFDR', false);

out_dir = fullfile(scores_dir_cropped, 'plots_state_percent');
if ~isfolder(out_dir), mkdir(out_dir); end

OUT_bar = plot_state_percent_bar_3h_baseline_vs_ambtemp_APPvsWT( ...
    rows_overall_ambtemp, out_dir, ...
    'minNperGroupForStats', 3, ...
    'useFDR', false);
%%
% After run_group_sleep_architecture_ambtemp_overall
load('/Users/margaridaseabra/24.11_cropped_ambtemp/group_overall_ambtemp/rows_overall_ambtemp.mat');  % gives rows_overall_ambtemp

out_dir = '/Users/margaridaseabra/24.11_ambtemp_analysis';

OUT_bouts = plot_bouts_3h_baseline_vs_ambtemp_APPvsWT(rows_overall_ambtemp, out_dir, ...
    'minNperGroupForStats', 3, ...
    'useFDR', true);
%% 3 hour baseline vs ambtemp bouts (analysis a) %% RUN THIS FOR PPT

% 3h bout-rate baseline vs ambtemp (Condition x Genotype)
rows_overall_ambtemp = readtable( ...
    '/Users/margaridaseabra/24.11_cropped_ambtemp/group_overall_ambtemp/rows_overall_ambtemp.csv');

out_dir_3h = '/Users/margaridaseabra/24.11_ambtemp_analysis';

OUT_bouts3h = plot_bout_rate_3h_baseline_vs_ambtemp_APPvsWT( ...
                  rows_overall_ambtemp, out_dir_3h, ...
                  'states', ["WK","MA","NREM","REM","SLEEP"], ...
                  'minNperGroupForStats', 2);


%% progression
rows_perhr = readtable('/Users/margaridaseabra/sleep_app_ach_warm/Sleep Architecture Analysis/group_out/group_per_hour.csv');
meta       = readtable('/Users/margaridaseabra/sleep_app_ach_warm/Ambtemp prep-3h-selection/ambtemp-times-all-mice.xlsx', ...
                       'VariableNamingRule','preserve');

out_dir = '/Users/margaridaseabra/24.11_ambtemp_progression';

OUT_prog = plot_bouts_per_hour_ambtemp_progression_APPvsWT( ...
              rows_perhr, meta, ["WK","MA","NREM","REM"], out_dir, ...
              'relHourRange',[-3 5], ...
              'ambWindow_h',3, ...
              'useFDRforStars',true);

%% progression with baseline for comparison
rows_perhr = readtable('/Users/margaridaseabra/sleep_app_ach_warm/Sleep Architecture Analysis/group_out/group_per_hour.csv');
meta       = readtable('/Users/margaridaseabra/sleep_app_ach_warm/Ambtemp prep-3h-selection/ambtemp-times-all-mice.xlsx', ...
                       'VariableNamingRule','preserve');

out_dir = '/Users/margaridaseabra/24.11_ambtemp_progression_withBaseline';

OUT_prog = plot_bouts_per_hour_ambtemp_progression_with_baseline_APPvsWT( ...
              rows_perhr, meta, ["WK","MA","NREM","REM"], out_dir, ...
              'relHourRange',[-3 5], ...
              'ambWindow_h',3, ...
              'showIDs',false, ...
              'useFDRforStars',false, ...
              'minNperGroupForStats',3);

%% duration

bout_out_dir = fullfile(group_dir, 'boutduration_ambtemp');
if ~isfolder(bout_out_dir)
    mkdir(bout_out_dir);
end

OUT_bout = make_boutduration_APPvsWT_baseline_vs_ambtemp( ...
                rows_overall_ambtemp, ...
                bout_out_dir, ...
                ["WK","MA","NREM","REM"]);
