
% addpath(genpath('/Users/margaridaseabra/sleep_app_ach_warm/Sleep Architecture Analysis/sleep_architecture_from_scores.m'));
% which -all sleep_architecture_from_scores

OUT = run_group_sleep_architecture('/Users/margaridaseabra/15.11scores', ...
    'pattern','*_scores_1Hz.csv', ...
    'codes', struct('WK',0,'NREM',1,'REM',2,'MA',15), ...
    'includeMA', true, ...
    'ma_thresh_sec', 15, ...
    'reclassify_short_wake_to_MA', true, ...
    'out_dir', fullfile(pwd,'group_out'));
   