% Basic (WK/NREM/REM only)
OUT = sleep_architecture_from_scores('mouse2_base_scores_1Hz.csv', ...
    'codes', struct('WK',0,'NREM',1,'REM',2,'MA',15), ...
    'includeMA', false, ...
    'out_prefix','mouse2_base');

% % If you also want MA columns:
% OUT_MA = sleep_architecture_from_scores('mouse2_base_scores_1Hz.csv', ...
%     'includeMA', true, ...
%     'out_prefix','mouse2_base_withMA');
