
% addpath(genpath('/Users/margaridaseabra/sleep_app_ach_warm/Sleep Architecture Analysis/sleep_architecture_from_scores.m'));
% which -all sleep_architecture_from_scores

OUT = run_group_sleep_architecture('/Users/margaridaseabra/24.11scores', ...
    'pattern','*_scored_scores_1Hz.csv', ...
    'codes', struct('WK',0,'NREM',1,'REM',2,'MA',15), ...
    'includeMA', true, ...
    'ma_thresh_sec', 15, ...
    'reclassify_short_wake_to_MA', true, ...
    'out_dir', fullfile(pwd,'group_out'));

%% Baseline comparison WT vs. APP % in each state
make_baseline_state_percent_APPvsWT(OUT.overall, OUT.out_dir);
%% Prism export
make_baseline_state_percent_APPvsWT_prism(OUT.overall, OUT.out_dir);
%%
make_ambtemp_state_percent_APPvsWT_prism(OUT.overall, OUT.out_dir);

%% Prism export 3h
make_ambtemp_sleeppercent_threePhase_APPvsWT_prism(OUT.per_hour, OUT.out_dir);
%%
make_baseline_sleeppercent_threePhase_APPvsWT_prism(OUT.per_hour, OUT.out_dir);
%%
make_drugs_sleeppercent_threePhase_APPvsWT_prism(OUT.per_hour, OUT.out_dir);

%% Prism export durations
OUT_boutdur_EL = run_baseline_boutduration_earlyLate( ...
    OUT.per_hour, OUT.out_dir, ...
    ["WK","MA","NREM","REM"], ...
    'earlyMaxHour', 2, ...
    'showIDs', false, ...
    'minNperGroup', 3);
%% Prism bouts per hour 
OUT_bouts = run_baseline_boutduration_threePhase_APPvsWT_prism( ...
    OUT.per_hour, OUT.out_dir, ["WK","MA","NREM","REM"], ...
    'showIDs', false, ...
    'pointStyle', 'bands', ...   % shaded SEM blur + mean line
    'showStars', true, ...
    'useFDRforStars', false);    % stars from raw p (exploratory)
%% Prism bouts per hour AmbTemp
OUT_bouts = run_ambtemp_boutduration_threePhase_APPvsWT_prism( ...
    OUT.per_hour, OUT.out_dir, ["WK","MA","NREM","REM"], ...
    'showIDs', false, ...
    'pointStyle', 'bands', ...   % shaded SEM blur + mean line
    'showStars', true, ...
    'useFDRforStars', false);    % stars from raw p (exploratory)
%% Prism bouts per hour Drugs
OUT_bouts = run_drugs_boutduration_threePhase_APPvsWT_prism( ...
    OUT.per_hour, OUT.out_dir, ["WK","MA","NREM","REM"], ...
    'showIDs', false, ...
    'pointStyle', 'bands', ...   % shaded SEM blur + mean line
    'showStars', true, ...
    'useFDRforStars', false);
%% boys vs girls
make_baseline_state_percent_APPvsWT(OUT.overall, OUT.out_dir, true);

%% Baseline comparison WT vs APP state percent
% Pretty thesis figure: no IDs, stars from FDR
OUT_state = make_baseline_state_percent_APPvsWT( ...
    OUT.overall, OUT.out_dir, false, ...
    'showIDs', false, ...
    'useFDRforStars', false);
OUT_state.stats   % table you can quote in the thesis

%% Baseline comparison WT vs APP bout per hour second version
OUT_bouts = make_baseline_total_bouts_per_hour_APPvsWT_2( ...
    OUT.per_hour, OUT.out_dir, ["WK","MA","NREM","REM"], ...
    'showIDs', false, ...
    'pointStyle', 'bands', ...   % shaded SEM blur + mean line
    'showStars', true, ...
    'useFDRforStars', false);    % stars from raw p (exploratory)
rows_perhr = OUT.per_hour;

ST_WK   = run_rm_anova_bouts(rows_perhr, "WK");
ST_MA   = run_rm_anova_bouts(rows_perhr, "MA");
ST_NREM = run_rm_anova_bouts(rows_perhr, "NREM");
ST_REM  = run_rm_anova_bouts(rows_perhr, "REM");
%% BOUTS PER HOUR AMBTEMP
%% Ambtemp comparison WT vs APP bout per hour second version
OUT_bouts = make_ambtemp_total_bouts_per_hour_APPvsWT_2( ...
    OUT.per_hour, OUT.out_dir, ["WK","MA","NREM","REM"], ...
    'showIDs', false, ...
    'pointStyle', 'bands', ...   % shaded SEM blur + mean line
    'showStars', true, ...
    'useFDRforStars', false);    % stars from raw p (exploratory)
rows_perhr = OUT.per_hour;
%%
%% Drugs comparison WT vs APP bout per hour second version
OUT_bouts = make_drugs_total_bouts_per_hour_APPvsWT_2( ...
    OUT.per_hour, OUT.out_dir, ["WK","MA","NREM","REM"], ...
    'showIDs', false, ...
    'pointStyle', 'bands', ...   % shaded SEM blur + mean line
    'showStars', true, ...
    'useFDRforStars', false);    % stars from raw p (exploratory)
rows_perhr = OUT.per_hour;
%%
ST_WK   = run_rm_anova_bouts(rows_perhr, "WK");
ST_MA   = run_rm_anova_bouts(rows_perhr, "MA");
ST_NREM = run_rm_anova_bouts(rows_perhr, "NREM");
ST_REM  = run_rm_anova_bouts(rows_perhr, "REM");
%%
% 1) Start from the full per-hour table
rows_perhr = OUT.per_hour;  % from your main pipeline

% 2) Detect & (optionally) remove outlier mice
[rows_no_out, OUTLIERS] = remove_outlier_mice_perhour(rows_perhr, ...
    ["WK","MA","NREM","REM"], ...
    'Method','median', ...        % robust
    'Threshold',3, ...            % 3x IQR-ish
    'Verbose',true);

%% Bouts per phase
OUT_bouts_EL = make_baseline_bouts_earlyLate_APPvsWT( ...
    OUT.per_hour, OUT.out_dir, ["WK","MA","NREM","REM"], ...
    'earlyHours', 0:3, ...
    'showIDs', false, ...
    'minNperGroup', 3);
%% % per phase
OUT_state_EL = make_baseline_sleeppercent_earlyLate_APPvsWT( ...
    OUT.per_hour, OUT.out_dir, ...
    ["WK","MA","NREM","REM","SLEEP"], ...
    'earlyHours', 0:3, ...
    'showIDs', false, ...
    'minNperGroup', 3);
%% duration
OUT_boutdur_overall = make_baseline_boutduration_APPvsWT( ...
    OUT.per_hour, OUT.out_dir, ...
    ["WK","MA","NREM","REM"], ...
    'showIDs', false, ...
    'useFDRforStars', false, ...
    'minNperGroupForStats', 3);
%% AMBTEMP
OUT_boutdur_overall = make_ambtemp_boutduration_APPvsWT( ...
    OUT.per_hour, OUT.out_dir, ...
    ["WK","MA","NREM","REM"], ...
    'showIDs', false, ...
    'useFDRforStars', false, ...
    'minNperGroupForStats', 3);

%% duration per phase
rows_perhr = OUT.per_hour;
out_dir    = OUT.out_dir;
OUT_boutdur_EL = run_baseline_boutduration_earlyLate( ...
    OUT.per_hour, OUT.out_dir, ...
    ["WK","MA","NREM","REM"], ...
    'earlyMaxHour', 2, ...
    'showIDs', false, ...
    'minNperGroup', 3);
%% <sleep fragmentation
%% 6) Micro-arousal fragmentation

fprintf('\n=== Running MA fragmentation analysis (baseline) ===\n');

OUT_MAfrag = run_MA_fragmentation_from_overall(OUT.overall, OUT.out_dir, ...
                                               'showIDs', false);
%% fragmentation index prism
%% baseline (always change the function for the right condition)
OUT_MA_frag = run_MA_fragmentation_threePhase_from_perhour_prism( ...
    OUT.per_hour, OUT.out_dir, 'showIDs', false);
%% ambtemp (always change the function for the right condition)
OUT_MA_frag = run_MA_fragmentation_threePhase_from_perhour_prism( ...
    OUT.per_hour, OUT.out_dir, 'showIDs', false);

%%
scoreDir = '/Users/margaridaseabra/24.11scores';
out_dir = '/Users/margaridaseabra/sleep_app_ach_warm/Sleep Architecture Analysis/group_out';
ALL_REM = build_REM_bout_table_from_scores(scoreDir);
%%
scoreDir = '/Users/margaridaseabra/24.11scores';

% REM (score 2)
ALL_REM = build_state_bout_table_from_scores(scoreDir, 2, ...
    'stateLabel',"REM");
OUT_prism_REM = export_baseline_REM_survival_forPrism(ALL_REM, out_dir, ...
    'baseline_cond',"baseline");   % or "ambtemp", etc.

%%
% NREM (score 1)
ALL_NREM = build_state_bout_table_from_scores(scoreDir, 1, ...
    'stateLabel',"NREM");

OUT_prism_NREM = export_baseline_REM_survival_forPrism(ALL_NREM, out_dir, ...
    'baseline_cond',"baseline");   % or "ambtemp", etc.
%%
% Baseline
OUT_REM_baseline = extract_bouts_for_prism_v3('/Users/margaridaseabra/24.11scores', ...
    'state', 'WK', ...
    'condition', 'ambtemp', ...
    'output', 'WAKE_ambtemp.csv');
%% SURVIVAL CURVES FOR PRISM
%% BASELINE
extract_bouts_copy_paste('/Users/margaridaseabra/24.11scores', 'REM', 'baseline');
%%
extract_bouts_copy_paste('/Users/margaridaseabra/24.11scores', 'NREM', 'baseline');

%% AMBIENT WARMING
%% Baseline crop to use in comparison with AMBTEMP – restrict to window defined in Excel
extract_bouts_copy_paste('/Users/margaridaseabra/24.11scores', 'REM', 'baseline', ...
    '/Users/margaridaseabra/sleep_app_ach_warm/Ambtemp prep-3h-selection/ambtemp-times-all-mice.xlsx');% Ambtemp – restrict to window defined in Excel

extract_bouts_copy_paste('/Users/margaridaseabra/24.11scores', 'NREM', 'baseline', ...
    '/Users/margaridaseabra/sleep_app_ach_warm/Ambtemp prep-3h-selection/ambtemp-times-all-mice.xlsx');
%% AMBTEMP CROP
% Ambtemp – restrict to window defined in Excel
extract_bouts_copy_paste('/Users/margaridaseabra/24.11scores', 'REM', 'ambtemp', ...
    '/Users/margaridaseabra/sleep_app_ach_warm/Ambtemp prep-3h-selection/ambtemp-times-all-mice.xlsx');

% Ambtemp – restrict to window defined in Excel
extract_bouts_copy_paste('/Users/margaridaseabra/24.11scores', 'NREM', 'ambtemp', ...
    '/Users/margaridaseabra/sleep_app_ach_warm/Ambtemp prep-3h-selection/ambtemp-times-all-mice.xlsx');

%% DRUGS CROP
% Ambtemp – restrict to window defined in Excel
extract_bouts_copy_paste('/Users/margaridaseabra/24.11scores', 'REM', 'drugs', ...
    '/Users/margaridaseabra/sleep_app_ach_warm/Drugs-AmbTemp-crop-3h+washout/drugs-times-all-mice.xlsx');

% Ambtemp – restrict to window defined in Excel
extract_bouts_copy_paste('/Users/margaridaseabra/24.11scores', 'NREM', 'drugs', ...
    '/Users/margaridaseabra/sleep_app_ach_warm/Drugs-AmbTemp-crop-3h+washout/drugs-times-all-mice.xlsx');