function plot_bouts_per_hour_baseline_APPvsWT(PERHOUR, out_dir, state_name)
% plot_bouts_per_hour_baseline_APPvsWT
% -------------------------------------------------------------------------
% ONE figure:
%   - baseline only
%   - bouts/hour over time (hour_idx)
%   - APP and WT overlaid in same axes
%   - coloured mean ± SEM curves
%   - individual mouse points with ID labels
%
% NO grey spaghetti lines.
%
% INPUTS:
%   PERHOUR     table generated by run_group_sleep_architecture
%   out_dir     output folder
%   state_name  'NREM', 'WK', 'REM', or 'MA'

    if nargin < 2 || isempty(out_dir)
        out_dir = pwd;
    end
    if nargin < 3 || isempty(state_name)
        state_name = 'NREM';
    end
    if ~isfolder(out_dir)
        mkdir(out_dir);
    end

    % --- filter baseline + desired state ---
    T = PERHOUR(strcmpi(PERHOUR.condition,'baseline') & ...
                strcmpi(PERHOUR.state, state_name), :);

    if isempty(T)
        warning('No baseline rows for state %s; skipping.', state_name);
        return;
    end

    % Colours
    COL_APP = [0.25 0.45 0.95];
    COL_WT  = [0.20 0.20 0.20];

    genotypes = {'APP','WT'};
    hrs = unique(T.hour_idx);

    fh = figure('Color','w','Name',...
        sprintf('Bouts per hour — %s baseline APP vs WT',state_name));
    hold on;

    xlim([min(hrs)-0.2, max(hrs)+0.2]);
    set(gca,'XTick',hrs);

    % --------- helper: mean ± SEM ----------
    function h_mean = plot_mean_sem(Tsub, col)
        all_hours = unique(Tsub.hour_idx);
        nH = numel(all_hours);
        mu = NaN(nH,1);
        se = NaN(nH,1);

        for h = 1:nH
            vals = Tsub.bouts_per_h(Tsub.hour_idx == all_hours(h));
            vals = vals(~isnan(vals));
            if isempty(vals), continue; end
            mu(h) = mean(vals);
            se(h) = std(vals) / sqrt(numel(vals));
        end

        h_mean = errorbar(all_hours, mu, se, 'o-', ...
            'LineWidth',1.5, 'MarkerSize',6, ...
            'Color', col, ...
            'MarkerFaceColor','w', ...
            'MarkerEdgeColor', col);
    end

    % --------- helper: scatter + mouse IDs ----------
    function plot_points(Tsub, col)
        jitter_amount = 0.10;  % horizontal jitter for visibility
        for h = hrs'
            rows_h = Tsub.hour_idx == h;
            T_h = Tsub(rows_h,:);
            if isempty(T_h), continue; end

            xvals = h + (rand(height(T_h),1)-0.5)*jitter_amount;
            yvals = T_h.bouts_per_h;

            scatter(xvals, yvals, 34, col, 'filled', ...
                'MarkerFaceColor',col, ...
                'MarkerEdgeColor','k', ...
                'LineWidth',0.5);

            % mouse ID labels
            for k = 1:height(T_h)
                text(xvals(k)+0.05, yvals(k), char(T_h.mouse(k)), ...
                     'FontSize',8, 'Color',col, ...
                     'HorizontalAlignment','left');
            end
        end
    end

    % -----------------------------------------------
    %                   PLOT APP
    % -----------------------------------------------
    Tapp = T(strcmpi(T.genotype,'APP'), :);
    hAPP = [];
    if ~isempty(Tapp)
        plot_points(Tapp, COL_APP);
        hAPP = plot_mean_sem(Tapp, COL_APP);
    end

    % -----------------------------------------------
    %                   PLOT WT
    % -----------------------------------------------
    Twt = T(strcmpi(T.genotype,'WT'), :);
    hWT = [];
    if ~isempty(Twt)
        plot_points(Twt, COL_WT);
        hWT = plot_mean_sem(Twt, COL_WT);
    end

    % -----------------------------------------------
    %                   FINISHING
    % -----------------------------------------------
    ylabel('Bouts per hour');
    xlabel('Hour');
    title(sprintf('Bouts per hour — %s | baseline (APP vs WT)', state_name));
    grid on; box on;

    % legend
    legH = []; legL = {};
    if ~isempty(hAPP), legH(end+1) = hAPP; legL{end+1} = 'APP'; end
    if ~isempty(hWT),  legH(end+1) = hWT;  legL{end+1} = 'WT';  end
    if ~isempty(legH)
        legend(legH, legL, 'Box','off','Location','best');
    end

    fname = fullfile(out_dir, ...
        sprintf('bouts_per_hour_%s_baseline_APPvsWT.png', lower(state_name)));
    exportgraphics(fh, fname, 'Resolution',300);
    fprintf('Saved %s\n', fname);
end
