GROUP = run_ach_batch_auto( ...
    '/Users/margaridaseabra/24.11_cropped_ambtemp', ...
    '/Users/margaridaseabra/24.11_cropped_ambtemp');
%% 2) Run group comparison plots (APP vs WT across conditions)
run_ach_group_plots(GROUP);
%%
group_plot_all_transitions_paper(GROUP);
%%
GROUP = run_ach_batch_auto_anova('/Users/margaridaseabra/24.11_cropped_ambtemp', '/Users/margaridaseabra/24.11_cropped_ambtemp', ...
                           'showMouseIDs', true, ...
                           'doANOVA', true);
