codes = struct('WK',0,'NREM',1,'REM',2,'MA',15);

%% Review REM episodes
review_REM_MA_tool( ...
    '/Users/margaridaseabra/24.11 signalnotscored/20251001_baseline_mouse1_APP.mat', ...
    '/Users/margaridaseabra/24.11scores/20251001_baseline_mouse1_APP_scored_scores_1Hz.csv', ...
    'REM', ...
    'codes', codes, ...
    'pre_sec', 20, ...
    'post_sec', 20, ...
    'min_dur_sec', 15, ...        % only REM ≥ 15 s
    'out_file', 'mouse1_APP_baseline_REM_flags.mat');

%% Review MA episodes
review_REM_MA_tool( ...
    '20251001_baseline_mouse1_APP.mat', ...
    '20251001_baseline_mouse1_APP_scored_scores_1Hz.csv', ...
    'MA', ...
    'codes', codes, ...
    'pre_sec', 20, ...
    'post_sec', 20, ...
    'min_dur_sec', 3, ...         % MAs are shorter
    'out_file', 'mouse1_APP_baseline_MA_flags.mat');
%%
EP = inspect_rem_viewer( ...
    '/Users/margaridaseabra/24.11 signalnotscored/20251001_baseline_mouse1_APP.mat', ...
    '/Users/margaridaseabra/24.11scores/20251001_baseline_mouse1_APP_scored_scores_1Hz.csv'); ...
