ach_state_event_analysis( ...
  '/Users/margaridaseabra/Downloads/scored files/20251023-drugs-mouse3_scored.mat', ...
  'events_csv', '/Users/margaridaseabra/sleep_app_ach_warm/events/20251023-drugs-mouse3_scored.csv');
