OUT = psd_sigma_theta_analysis( ...
          '/Users/margaridaseabra/Library/CloudStorage/OneDrive-UniversityofCopenhagen/scored files/20251002-mouse2-baseline_test.mat', ...
          '/Users/margaridaseabra/Library/CloudStorage/OneDrive-UniversityofCopenhagen/scored files/mouse2_base_scores_1Hz.csv', ...
          'mouse_id','M2', ...
          'session','baseline', ...
          'epoch_sec',1);
