%% DRUGS
scores_dir_drug = '/Users/margaridaseabra/24.11scores';
mats_dir_drug   = '/Users/margaridaseabra/24.11 signalnotscored';
out_dir_drug    = '/Users/margaridaseabra/24.11_cropped_drugs';

OUT_drug = crop_segments( ...
    '/Users/margaridaseabra/sleep_app_ach_warm/Drugs prep/drugs-times-all-mice.xlsx', ...
    scores_dir_drug, ...
    mats_dir_drug, ...
    out_dir_drug, ...
    'conditions', "drugs");  
%% AMBTEMP
scores_dir_drug = '/Users/margaridaseabra/24.11scores';
mats_dir_drug   = '/Users/margaridaseabra/24.11 signalnotscored';
out_dir_drug    = '/Users/margaridaseabra/24.11_cropped_ambtemp_washout';

OUT_drug = crop_segments( ...
    '/Users/margaridaseabra/sleep_app_ach_warm/Drugs-AmbTemp-crop-3h+washout/ambtemp-times-all-mice.xlsx', ...
    scores_dir_drug, ...
    mats_dir_drug, ...
    out_dir_drug, ...
    'conditions', "ambtemp");  
%% BASELINE
scores_dir_drug = '/Users/margaridaseabra/24.11scores';
mats_dir_drug   = '/Users/margaridaseabra/24.11 signalnotscored';
out_dir_drug    = '/Users/margaridaseabra/24.11_cropped_baseline_washout';

OUT_drug = crop_segments( ...
    '/Users/margaridaseabra/sleep_app_ach_warm/Drugs-AmbTemp-crop-3h+washout/ambtemp-times-all-mice.xlsx', ...
    scores_dir_drug, ...
    mats_dir_drug, ...
    out_dir_drug, ...
    'conditions', "baseline");  